/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'primary': 'rgb(var(--color-primary) / <alpha-value>)',
        'primary-50': 'rgb(var(--color-primary-50) / <alpha-value>)',
        'primary-100': 'rgb(var(--color-primary-100) / <alpha-value>)',
        'primary-200': 'rgb(var(--color-primary-200) / <alpha-value>)',
        'primary-300': 'rgb(var(--color-primary-300) / <alpha-value>)',
        'primary-400': 'rgb(var(--color-primary-400) / <alpha-value>)',
        'primary-500': 'rgb(var(--color-primary-500) / <alpha-value>)',
        'primary-600': 'rgb(var(--color-primary-600) / <alpha-value>)',
        'primary-700': 'rgb(var(--color-primary-700) / <alpha-value>)',
        'primary-800': 'rgb(var(--color-primary-800) / <alpha-value>)',
        'primary-900': 'rgb(var(--color-primary-900) / <alpha-value>)',
        'primary-950': 'rgb(var(--color-primary-950) / <alpha-value>)',
        'primary-foreground': 'rgb(var(--color-primary-foreground) / <alpha-value>)',

        'secondary': 'rgb(var(--color-secondary) / <alpha-value>)',
        'secondary-50': 'rgb(var(--color-secondary-50) / <alpha-value>)',
        'secondary-100': 'rgb(var(--color-secondary-100) / <alpha-value>)',
        'secondary-200': 'rgb(var(--color-secondary-200) / <alpha-value>)',
        'secondary-300': 'rgb(var(--color-secondary-300) / <alpha-value>)',
        'secondary-400': 'rgb(var(--color-secondary-400) / <alpha-value>)',
        'secondary-500': 'rgb(var(--color-secondary-500) / <alpha-value>)',
        'secondary-600': 'rgb(var(--color-secondary-600) / <alpha-value>)',
        'secondary-700': 'rgb(var(--color-secondary-700) / <alpha-value>)',
        'secondary-800': 'rgb(var(--color-secondary-800) / <alpha-value>)',
        'secondary-900': 'rgb(var(--color-secondary-900) / <alpha-value>)',
        'secondary-950': 'rgb(var(--color-secondary-950) / <alpha-value>)',
        'secondary-foreground': 'rgb(var(--color-secondary-foreground) / <alpha-value>)',

        'accent': 'rgb(var(--color-accent) / <alpha-value>)',
        'accent-50': 'rgb(var(--color-accent-50) / <alpha-value>)',
        'accent-100': 'rgb(var(--color-accent-100) / <alpha-value>)',
        'accent-200': 'rgb(var(--color-accent-200) / <alpha-value>)',
        'accent-300': 'rgb(var(--color-accent-300) / <alpha-value>)',
        'accent-400': 'rgb(var(--color-accent-400) / <alpha-value>)',
        'accent-500': 'rgb(var(--color-accent-500) / <alpha-value>)',
        'accent-600': 'rgb(var(--color-accent-600) / <alpha-value>)',
        'accent-700': 'rgb(var(--color-accent-700) / <alpha-value>)',
        'accent-800': 'rgb(var(--color-accent-800) / <alpha-value>)',
        'accent-900': 'rgb(var(--color-accent-900) / <alpha-value>)',
        'accent-950': 'rgb(var(--color-accent-950) / <alpha-value>)',
        'accent-foreground': 'rgb(var(--color-accent-foreground) / <alpha-value>)',

        'success': 'rgb(var(--color-success) / <alpha-value>)',
        'success-50': 'rgb(var(--color-success-50) / <alpha-value>)',
        'success-100': 'rgb(var(--color-success-100) / <alpha-value>)',
        'success-200': 'rgb(var(--color-success-200) / <alpha-value>)',
        'success-300': 'rgb(var(--color-success-300) / <alpha-value>)',
        'success-400': 'rgb(var(--color-success-400) / <alpha-value>)',
        'success-500': 'rgb(var(--color-success-500) / <alpha-value>)',
        'success-600': 'rgb(var(--color-success-600) / <alpha-value>)',
        'success-700': 'rgb(var(--color-success-700) / <alpha-value>)',
        'success-800': 'rgb(var(--color-success-800) / <alpha-value>)',
        'success-900': 'rgb(var(--color-success-900) / <alpha-value>)',
        'success-950': 'rgb(var(--color-success-950) / <alpha-value>)',
        'success-foreground': 'rgb(var(--color-success-foreground) / <alpha-value>)',

        'warning': 'rgb(var(--color-warning) / <alpha-value>)',
        'warning-50': 'rgb(var(--color-warning-50) / <alpha-value>)',
        'warning-100': 'rgb(var(--color-warning-100) / <alpha-value>)',
        'warning-200': 'rgb(var(--color-warning-200) / <alpha-value>)',
        'warning-300': 'rgb(var(--color-warning-300) / <alpha-value>)',
        'warning-400': 'rgb(var(--color-warning-400) / <alpha-value>)',
        'warning-500': 'rgb(var(--color-warning-500) / <alpha-value>)',
        'warning-600': 'rgb(var(--color-warning-600) / <alpha-value>)',
        'warning-700': 'rgb(var(--color-warning-700) / <alpha-value>)',
        'warning-800': 'rgb(var(--color-warning-800) / <alpha-value>)',
        'warning-900': 'rgb(var(--color-warning-900) / <alpha-value>)',
        'warning-950': 'rgb(var(--color-warning-950) / <alpha-value>)',
        'warning-foreground': 'rgb(var(--color-warning-foreground) / <alpha-value>)',

        'error': 'rgb(var(--color-error) / <alpha-value>)',
        'error-50': 'rgb(var(--color-error-50) / <alpha-value>)',
        'error-100': 'rgb(var(--color-error-100) / <alpha-value>)',
        'error-200': 'rgb(var(--color-error-200) / <alpha-value>)',
        'error-300': 'rgb(var(--color-error-300) / <alpha-value>)',
        'error-400': 'rgb(var(--color-error-400) / <alpha-value>)',
        'error-500': 'rgb(var(--color-error-500) / <alpha-value>)',
        'error-600': 'rgb(var(--color-error-600) / <alpha-value>)',
        'error-700': 'rgb(var(--color-error-700) / <alpha-value>)',
        'error-800': 'rgb(var(--color-error-800) / <alpha-value>)',
        'error-900': 'rgb(var(--color-error-900) / <alpha-value>)',
        'error-950': 'rgb(var(--color-error-950) / <alpha-value>)',
        'error-foreground': 'rgb(var(--color-error-foreground) / <alpha-value>)',

        'background': 'rgb(var(--color-background) / <alpha-value>)',
        'foreground': 'rgb(var(--color-foreground) / <alpha-value>)',
        'surface': 'rgb(var(--color-surface) / <alpha-value>)',
        'surface-foreground': 'rgb(var(--color-surface-foreground) / <alpha-value>)',
        'border': 'rgb(var(--color-border) / <alpha-value>)',
        'border-muted': 'rgb(var(--color-border-muted) / <alpha-value>)',
        'ring': 'rgb(var(--color-ring) / <alpha-value>)',

        'text-primary': 'rgb(var(--color-text-primary) / <alpha-value>)',
        'text-secondary': 'rgb(var(--color-text-secondary) / <alpha-value>)',
        'text-muted': 'rgb(var(--color-text-muted) / <alpha-value>)',
        'text-accent': 'rgb(var(--color-text-accent) / <alpha-value>)',
      },
      fontFamily: {
        'heading': ['Inter', 'system-ui', 'sans-serif'],
        'body': ['Inter', 'system-ui', 'sans-serif'],
        'caption': ['Inter', 'system-ui', 'sans-serif'],
        'data': ['JetBrains Mono', 'Consolas', 'Monaco', 'monospace'],
      },
      fontSize: {
        'xs': ['0.75rem', { lineHeight: '1rem' }],
        'sm': ['0.875rem', { lineHeight: '1.25rem' }],
        'base': ['1rem', { lineHeight: '1.5rem' }],
        'lg': ['1.125rem', { lineHeight: '1.75rem' }],
        'xl': ['1.25rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
      },
      fontWeight: {
        'normal': '400',
        'medium': '500',
        'semibold': '600',
      },
      borderRadius: {
        'sm': '4px',
        'DEFAULT': '6px',
        'md': '6px',
        'lg': '8px',
        'xl': '12px',
      },
      boxShadow: {
        'elevation-1': '0 1px 3px rgba(0, 0, 0, 0.1), 0 1px 2px rgba(0, 0, 0, 0.06)',
        'elevation-2': '0 4px 6px rgba(0, 0, 0, 0.05), 0 2px 4px rgba(0, 0, 0, 0.06)',
        'elevation-3': '0 10px 15px rgba(0, 0, 0, 0.1), 0 4px 6px rgba(0, 0, 0, 0.05)',
        'elevation-4': '0 20px 25px rgba(0, 0, 0, 0.1), 0 10px 10px rgba(0, 0, 0, 0.04)',
      },
      animation: {
        'pulse-subtle': 'pulse-subtle 1.5s ease-in-out infinite',
        'fade-in': 'fadeIn 0.3s ease-out',
        'slide-in-left': 'slideInLeft 0.3s ease-out',
        'slide-out-left': 'slideOutLeft 0.3s ease-out',
      },
      keyframes: {
        'pulse-subtle': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.4' },
        },
        'fadeIn': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'slideInLeft': {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(0)' },
        },
        'slideOutLeft': {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-100%)' },
        },
      },
      transitionDuration: {
        'fast': '150ms',
        'normal': '300ms',
        'slow': '500ms',
      },
      transitionTimingFunction: {
        'ease-out': 'cubic-bezier(0, 0, 0.2, 1)',
      },
      spacing: {
        '18': '4.5rem',
        '88': '22rem',
      },
      zIndex: {
        '1000': '1000',
        '1010': '1010',
        '1020': '1020',
        '1030': '1030',
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
    require('@tailwindcss/forms'),
    require('tailwindcss-animate'),
  ],
}